//
// Created by zhou on 24-3-3.
//

#ifndef BASIC_KITS_DATA_DEFS_H
#define BASIC_KITS_DATA_DEFS_H


// copy from OpenCV
// opencv2/core/hal/interface.h

#define ZZQ_DT_CN_MAX     512
#define ZZQ_DT_CN_SHIFT   3
#define ZZQ_DT_DEPTH_MAX  (1 << ZZQ_DT_CN_SHIFT)

#define ZZQ_DT_8U   0
#define ZZQ_DT_8S   1
#define ZZQ_DT_16U  2
#define ZZQ_DT_16S  3
#define ZZQ_DT_32S  4
#define ZZQ_DT_32F  5
#define ZZQ_DT_64F  6
#define ZZQ_DT_16F  7


#define ZZQ_DT_MAT_DEPTH_MASK       (ZZQ_DT_DEPTH_MAX - 1)
#define ZZQ_DT_MAT_DEPTH(flags)     ((flags) & ZZQ_DT_MAT_DEPTH_MASK)

#define ZZQ_DT_MAKETYPE(depth,cn) (ZZQ_DT_MAT_DEPTH(depth) + (((cn)-1) << ZZQ_DT_CN_SHIFT))
#define ZZQ_DT_MAKE_TYPE ZZQ_DT_MAKETYPE

#define ZZQ_DT_8UC1 ZZQ_DT_MAKETYPE(ZZQ_DT_8U,1)
#define ZZQ_DT_8UC2 ZZQ_DT_MAKETYPE(ZZQ_DT_8U,2)
#define ZZQ_DT_8UC3 ZZQ_DT_MAKETYPE(ZZQ_DT_8U,3)
#define ZZQ_DT_8UC4 ZZQ_DT_MAKETYPE(ZZQ_DT_8U,4)
#define ZZQ_DT_8UC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_8U,(n))

#define ZZQ_DT_8SC1 ZZQ_DT_MAKETYPE(ZZQ_DT_8S,1)
#define ZZQ_DT_8SC2 ZZQ_DT_MAKETYPE(ZZQ_DT_8S,2)
#define ZZQ_DT_8SC3 ZZQ_DT_MAKETYPE(ZZQ_DT_8S,3)
#define ZZQ_DT_8SC4 ZZQ_DT_MAKETYPE(ZZQ_DT_8S,4)
#define ZZQ_DT_8SC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_8S,(n))

#define ZZQ_DT_16UC1 ZZQ_DT_MAKETYPE(ZZQ_DT_16U,1)
#define ZZQ_DT_16UC2 ZZQ_DT_MAKETYPE(ZZQ_DT_16U,2)
#define ZZQ_DT_16UC3 ZZQ_DT_MAKETYPE(ZZQ_DT_16U,3)
#define ZZQ_DT_16UC4 ZZQ_DT_MAKETYPE(ZZQ_DT_16U,4)
#define ZZQ_DT_16UC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_16U,(n))

#define ZZQ_DT_16SC1 ZZQ_DT_MAKETYPE(ZZQ_DT_16S,1)
#define ZZQ_DT_16SC2 ZZQ_DT_MAKETYPE(ZZQ_DT_16S,2)
#define ZZQ_DT_16SC3 ZZQ_DT_MAKETYPE(ZZQ_DT_16S,3)
#define ZZQ_DT_16SC4 ZZQ_DT_MAKETYPE(ZZQ_DT_16S,4)
#define ZZQ_DT_16SC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_16S,(n))

#define ZZQ_DT_32SC1 ZZQ_DT_MAKETYPE(ZZQ_DT_32S,1)
#define ZZQ_DT_32SC2 ZZQ_DT_MAKETYPE(ZZQ_DT_32S,2)
#define ZZQ_DT_32SC3 ZZQ_DT_MAKETYPE(ZZQ_DT_32S,3)
#define ZZQ_DT_32SC4 ZZQ_DT_MAKETYPE(ZZQ_DT_32S,4)
#define ZZQ_DT_32SC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_32S,(n))

#define ZZQ_DT_32FC1 ZZQ_DT_MAKETYPE(ZZQ_DT_32F,1)
#define ZZQ_DT_32FC2 ZZQ_DT_MAKETYPE(ZZQ_DT_32F,2)
#define ZZQ_DT_32FC3 ZZQ_DT_MAKETYPE(ZZQ_DT_32F,3)
#define ZZQ_DT_32FC4 ZZQ_DT_MAKETYPE(ZZQ_DT_32F,4)
#define ZZQ_DT_32FC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_32F,(n))

#define ZZQ_DT_64FC1 ZZQ_DT_MAKETYPE(ZZQ_DT_64F,1)
#define ZZQ_DT_64FC2 ZZQ_DT_MAKETYPE(ZZQ_DT_64F,2)
#define ZZQ_DT_64FC3 ZZQ_DT_MAKETYPE(ZZQ_DT_64F,3)
#define ZZQ_DT_64FC4 ZZQ_DT_MAKETYPE(ZZQ_DT_64F,4)
#define ZZQ_DT_64FC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_64F,(n))

#define ZZQ_DT_16FC1 ZZQ_DT_MAKETYPE(ZZQ_DT_16F,1)
#define ZZQ_DT_16FC2 ZZQ_DT_MAKETYPE(ZZQ_DT_16F,2)
#define ZZQ_DT_16FC3 ZZQ_DT_MAKETYPE(ZZQ_DT_16F,3)
#define ZZQ_DT_16FC4 ZZQ_DT_MAKETYPE(ZZQ_DT_16F,4)
#define ZZQ_DT_16FC(n) ZZQ_DT_MAKETYPE(ZZQ_DT_16F,(n))

#define ZZQ_ALIGN_UP(value, align) (((value)+((align)-1))&(~((align)-1)))
#define ZZQ_ALIGN_DOWN(value, align) ((value)&(~((align)-1)))
#define ZZQ_ALIGN_AROUND(value, align) (((value)+(align)/2)/(align)*(align))

#define ZZQ_GET_MAX(a, b)  ((a) > (b) ? (a) : (b))
#define ZZQ_GET_MIN(a, b)  ((a) < (b) ? (a) : (b))

#endif //BASIC_KITS_DATA_DEFS_H
